import './globals.css';
import { IBM_Plex_Sans } from 'next/font/google';

const imbPlexSans = IBM_Plex_Sans({
  weight: '500',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Coffee Connoisseur',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={imbPlexSans.className}>{children}</body>
    </html>
  );
}
